### ISSUE TITLE
Admin: Searching with 'Online Between' and a condition is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1809]
Searching for:
![image](https://cloud.githubusercontent.com/assets/3857942/20114994/9566adae-a5c4-11e6-8d7a-fa921e8777c9.png)

Yields a lot of devices, if I pick one and search for:
![image](https://cloud.githubusercontent.com/assets/3857942/20115033/b22a0efe-a5c4-11e6-8048-61c275266492.png)

This returns nothing even though 00:11:22:33:44:55 was part of the MAC addresses that were returned in the previous search.

This is on 6.0 with all patches applied up to maintenance/6.0 e42793933d2f0700fd3c99c1e6ca6d3a733a63d7 (no new patch related to the admin since then)

I have checked and there are accounting records for the affected MAC addresses that are in the right range

**Comment by julsemaan** [comment]
First, I tried the patch and it didn't fix the issue.
I believe you should first validate with the submitter whether your patch fixes their issue before you close it.
Even more, you shouldn't cherry-pick it in the maintenance before the submitter confirms it actually fixes it.

Second, after looking at your patch that 'normalizes' the MAC address when searching in accounting, it normalizes it to a format that isn't even valid.
The callingstationid has been normalized at insert in the DB to be of the format aa:aa:aa:aa:aa:aa so it fits with our standard so your patch looks like its actually making things worst.

**Comment by jrouzierinverse** [comment]
Hmm the data I have may have been bad since the callingstationid in my db is normalized to XYXYXYXYXYXY.
Can you provide me with the output of the following.

```
select * from radacct where callingstationid IN ('001122334455', '00:11:22:33:44:55')  LIMIT 50;
```

**Comment by jrouzierinverse** [comment]
Also the following query

```
select DISTINCT callingstationid from radacct where acctstarttime >= '2011-11-07 00:00:00' and acctstoptime <= '2016-11-09 23:59:59';
```

**Comment by julsemaan** [comment]
Here you go (had to fake a few fields as this comes from the environment in question): 

```
*************************** 1. row ***************************
         radacctid: 244166
     acctsessionid: 5755ab19/00:11:22:33:44:55/7592624
      acctuniqueid: 12345678901234567890
          username: donaldtrump
         groupname: 
             realm: null
      nasipaddress: 1.2.3.4
         nasportid: 4
       nasporttype: Wireless-802.11
     acctstarttime: 2016-06-06 11:55:53
    acctupdatetime: 2016-06-06 13:11:55
      acctstoptime: NULL
      acctinterval: 12
   acctsessiontime: 4562
     acctauthentic: RADIUS
 connectinfo_start: 
  connectinfo_stop: 
   acctinputoctets: 272288
  acctoutputoctets: 1318349
   calledstationid: 69:69:69:69:69:69
  callingstationid: 00:11:22:33:44:55
acctterminatecause: 
       servicetype: 
    framedprotocol: 
   framedipaddress: 1.2.3.4
```
