### ISSUE TITLE
Admin nodes: Issue when searching node with partial accounting data

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2824]
If a node has only partial accounting data which can be the result of a cleanup or missed packet, then searching for that node gives no result:

Accounting data for node:
```
mysql> select * from radacct where callingstationid="00:11:22:33:44:55"\G
*************************** 1. row ***************************
         radacctid: 194679
     acctsessionid: 581A4CE3-000105D3
      acctuniqueid: 875645fd236bbdb109bcfd12a5c9b60a
          username: bobby
         groupname:
             realm: null
      nasipaddress: 10.1.0.8
         nasportid: 20481
       nasporttype: Wireless-802.11
     acctstarttime: NULL
    acctupdatetime: 2016-11-29 08:46:11
      acctstoptime: NULL
      acctinterval: NULL
   acctsessiontime: NULL
     acctauthentic: RADIUS
 connectinfo_start: CONNECT 802.11g
  connectinfo_stop: NULL
   acctinputoctets: 0
  acctoutputoctets: 0
   calledstationid: 00:11:22:33:44:56:Zammitcorp-Secure
  callingstationid: 00:11:22:33:44:55
acctterminatecause:
       servicetype:
    framedprotocol:
   framedipaddress: 10.33.81.65
1 row in set (0.00 sec)
```

Deleting this row makes the search yield a result, with this row, then there is no result while searching for the node.

This happens on 6.2, will try to replicate on devel
