### ISSUE TITLE
Default node view in the admin requires a full table scan

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#3721]
When viewing the nodes in the admin, it requires a full table scan to view the first 25 rows because the default order uses the MAC address without the tenant ID which doesn't use indexing

Explains:
```

MariaDB [pf]> EXPLAIN SELECT `node`.`mac` AS `mac`, `node`.`pid` AS `pid`, `node`.`voip` AS `voip`, `node`.`bypass_vlan` AS `bypass_vlan`, `node`.`status` AS `status`, `node`.`category_id` AS `category_id`, `node`.`bypass_role_id` AS `bypass_role_id`, `node`.`user_agent` AS `user_agent`, `node`.`computername` AS `computername`, `node`.`last_arp` AS `last_arp`, `node`.`last_dhcp` AS `last_dhcp`, `node`.`notes` AS `notes`, `node`.`tenant_id` AS `tenant_id`, IF(lastskip='0000-00-00 00:00:00','',lastskip) AS `lastskip`, IF(detect_date='0000-00-00 00:00:00','',detect_date) AS `detect_date`, IF(regdate='0000-00-00 00:00:00','',regdate) AS `regdate`, IF(unregdate='0000-00-00 00:00:00','',unregdate) AS `unregdate`, IF(last_seen='0000-00-00 00:00:00','',last_seen) AS `last_seen`, IFNULL(node_category.name, '') AS `category`, IFNULL(node_category_bypass_role.name, '') AS `bypass_role`, IFNULL(device_manufacturer,' ') AS `device_manufacturer`, IFNULL(device_class,' ') AS `device_class`, IFNULL(device_type,' ') AS `device_type`, IFNULL(device_version,' ') AS `device_version`, IF(r1.acctstarttime IS NULL,'unknown',IF(r1.acctstoptime IS NULL, 'on', 'off')) AS `online`, `ip4log`.`ip` AS `last_ip`, `locationlog`.`switch` AS `switch_id`, `locationlog`.`switch_ip` AS `switch_ip`, `locationlog`.`switch_mac` AS `switch_mac`, `locationlog`.`port` AS `switch_port`, `locationlog`.`ifDesc` AS `switch_port_desc`, `locationlog`.`ssid` AS `last_ssid`, `tenant`.`name` AS `tenant_name` FROM node LEFT OUTER JOIN node_category ON ( `node`.`category_id` = `node_category`.`category_id` ) LEFT OUTER JOIN tenant ON ( `node`.`tenant_id` = `tenant`.`id` ) LEFT OUTER JOIN `node_category` AS `node_category_bypass_role` ON ( `node`.`bypass_role_id` = `node_category_bypass_role`.`category_id` ) LEFT OUTER JOIN ip4log ON ( ( `ip4log`.`ip` = ( SELECT `ip` FROM `ip4log` WHERE `mac` = `node`.`mac` AND `tenant_id` = `node`.`tenant_id`  ORDER BY `start_time` DESC LIMIT 1 ) AND `ip4log`.`tenant_id` = `node`.`tenant_id` ) ) LEFT OUTER JOIN locationlog ON ( ( `locationlog`.`end_time` = '0000-00-00 00:00:00' AND `locationlog`.`mac` = `node`.`mac` AND `node`.`tenant_id` = `locationlog`.`tenant_id` ) ) LEFT OUTER JOIN `locationlog` AS `locationlog2` ON ( ( ( `locationlog`.`start_time` < `locationlog2`.`start_time` OR `locationlog`.`start_time` IS NULL OR ( `locationlog`.`start_time` = `locationlog2`.`start_time` AND `locationlog`.`id` < `locationlog2`.`id` ) ) AND `locationlog2`.`end_time` = '0000-00-00 00:00:00' AND `node`.`mac` = `locationlog2`.`mac` AND `node`.`tenant_id` = `locationlog2`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r1` ON ( ( `node`.`mac` = `r1`.`callingstationid` AND `node`.`tenant_id` = `r1`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r2` ON ( ( ( `r1`.`acctstarttime` < `r2`.`acctstarttime` OR ( ( `r1`.`acctstarttime` = `r2`.`acctstarttime` OR ( `r1`.`acctstarttime` IS NULL AND `r2`.`acctstarttime` IS NULL ) ) AND `r1`.`radacctid` < `r2`.`radacctid` ) ) AND `node`.`mac` = `r2`.`callingstationid` AND `node`.`tenant_id` = `r2`.`tenant_id` ) ) WHERE ( ( `r2`.`radacctid` IS NULL AND `locationlog2`.`id` IS NULL ) ) ORDER BY `mac` ASC LIMIT 26 OFFSET 0;
+------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
| id   | select_type        | table                     | type   | possible_keys                                     | key                  | key_len | ref                    | rows | Extra                                              |
+------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
|    1 | PRIMARY            | node                      | ALL    | NULL                                              | NULL                 | NULL    | NULL                   |  144 | Using filesort                                     |
|    1 | PRIMARY            | node_category             | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.category_id    |    1 | Using where                                        |
|    1 | PRIMARY            | tenant                    | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.tenant_id      |    1 |                                                    |
|    1 | PRIMARY            | node_category_bypass_role | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.bypass_role_id |    1 | Using where                                        |
|    1 | PRIMARY            | ip4log                    | eq_ref | PRIMARY                                           | PRIMARY              | 51      | pf.node.tenant_id,func |    1 | Using where; Using index                           |
|    1 | PRIMARY            | locationlog               | ref    | locationlog_view_mac,locationlog_end_time         | locationlog_view_mac | 25      | pf.node.mac,const      |    1 | Using where                                        |
|    1 | PRIMARY            | locationlog2              | ref    | PRIMARY,locationlog_view_mac,locationlog_end_time | locationlog_view_mac | 25      | pf.node.mac,const      |    1 | Using where; Not exists                            |
|    1 | PRIMARY            | r1                        | ref    | callingstationid                                  | callingstationid     | 52      | pf.node.mac            |    5 | Using where                                        |
|    1 | PRIMARY            | r2                        | ref    | PRIMARY,callingstationid,acctstart_acctstop       | callingstationid     | 52      | pf.node.mac            |    5 | Using where; Not exists                            |
|    2 | DEPENDENT SUBQUERY | ip4log                    | ref    | PRIMARY,ip4log_mac_end_time                       | ip4log_mac_end_time  | 19      | pf.node.mac            |    1 | Using index condition; Using where; Using filesort |
+------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
10 rows in set (0.04 sec)
```

```
MariaDB [pf]> EXPLAIN SELECT `node`.`mac` AS `mac`, `node`.`pid` AS `pid`, `node`.`voip` AS `voip`, `node`.`bypass_vlan` AS `bypass_vlan`, `node`.`status` AS `status`, `node`.`category_id` AS `category_id`, `node`.`bypass_role_id` AS `bypass_role_id`, `node`.`user_agent` AS `user_agent`, `node`.`computername` AS `computername`, `node`.`last_arp` AS `last_arp`, `node`.`last_dhcp` AS `last_dhcp`, `node`.`notes` AS `notes`, `node`.`tenant_id` AS `tenant_id`, IF(lastskip='0000-00-00 00:00:00','',lastskip) AS `lastskip`, IF(detect_date='0000-00-00 00:00:00','',detect_date) AS `detect_date`, IF(regdate='0000-00-00 00:00:00','',regdate) AS `regdate`, IF(unregdate='0000-00-00 00:00:00','',unregdate) AS `unregdate`, IF(last_seen='0000-00-00 00:00:00','',last_seen) AS `last_seen`, IFNULL(node_category.name, '') AS `category`, IFNULL(node_category_bypass_role.name, '') AS `bypass_role`, IFNULL(device_manufacturer,' ') AS `device_manufacturer`, IFNULL(device_class,' ') AS `device_class`, IFNULL(device_type,' ') AS `device_type`, IFNULL(device_version,' ') AS `device_version`, IF(r1.acctstarttime IS NULL,'unknown',IF(r1.acctstoptime IS NULL, 'on', 'off')) AS `online`, `ip4log`.`ip` AS `last_ip`, `locationlog`.`switch` AS `switch_id`, `locationlog`.`switch_ip` AS `switch_ip`, `locationlog`.`switch_mac` AS `switch_mac`, `locationlog`.`port` AS `switch_port`, `locationlog`.`ifDesc` AS `switch_port_desc`, `locationlog`.`ssid` AS `last_ssid`, `tenant`.`name` AS `tenant_name` FROM node LEFT OUTER JOIN node_category ON ( `node`.`category_id` = `node_category`.`category_id` ) LEFT OUTER JOIN tenant ON ( `node`.`tenant_id` = `tenant`.`id` ) LEFT OUTER JOIN `node_category` AS `node_category_bypass_role` ON ( `node`.`bypass_role_id` = `node_category_bypass_role`.`category_id` ) LEFT OUTER JOIN ip4log ON ( ( `ip4log`.`ip` = ( SELECT `ip` FROM `ip4log` WHERE `mac` = `node`.`mac` AND `tenant_id` = `node`.`tenant_id`  ORDER BY `start_time` DESC LIMIT 1 ) AND `ip4log`.`tenant_id` = `node`.`tenant_id` ) ) LEFT OUTER JOIN locationlog ON ( ( `locationlog`.`end_time` = '0000-00-00 00:00:00' AND `locationlog`.`mac` = `node`.`mac` AND `node`.`tenant_id` = `locationlog`.`tenant_id` ) ) LEFT OUTER JOIN `locationlog` AS `locationlog2` ON ( ( ( `locationlog`.`start_time` < `locationlog2`.`start_time` OR `locationlog`.`start_time` IS NULL OR ( `locationlog`.`start_time` = `locationlog2`.`start_time` AND `locationlog`.`id` < `locationlog2`.`id` ) ) AND `locationlog2`.`end_time` = '0000-00-00 00:00:00' AND `node`.`mac` = `locationlog2`.`mac` AND `node`.`tenant_id` = `locationlog2`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r1` ON ( ( `node`.`mac` = `r1`.`callingstationid` AND `node`.`tenant_id` = `r1`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r2` ON ( ( ( `r1`.`acctstarttime` < `r2`.`acctstarttime` OR ( ( `r1`.`acctstarttime` = `r2`.`acctstarttime` OR ( `r1`.`acctstarttime` IS NULL AND `r2`.`acctstarttime` IS NULL ) ) AND `r1`.`radacctid` < `r2`.`radacctid` ) ) AND `node`.`mac` = `r2`.`callingstationid` AND `node`.`tenant_id` = `r2`.`tenant_id` ) ) WHERE ( ( `r2`.`radacctid` IS NULL AND `locationlog2`.`id` IS NULL ) ) ORDER BY `tenant_id`, `mac` ASC LIMIT 26 OFFSET 0;                                                                         +------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
| id   | select_type        | table                     | type   | possible_keys                                     | key                  | key_len | ref                    | rows | Extra                                              |
+------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
|    1 | PRIMARY            | node                      | index  | NULL                                              | PRIMARY              | 23      | NULL                   |    1 |                                                    |
|    1 | PRIMARY            | node_category             | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.category_id    |    1 | Using where                                        |
|    1 | PRIMARY            | tenant                    | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.tenant_id      |    1 |                                                    |
|    1 | PRIMARY            | node_category_bypass_role | eq_ref | PRIMARY                                           | PRIMARY              | 4       | pf.node.bypass_role_id |    1 | Using where                                        |
|    1 | PRIMARY            | ip4log                    | eq_ref | PRIMARY                                           | PRIMARY              | 51      | pf.node.tenant_id,func |    1 | Using where; Using index                           |
|    1 | PRIMARY            | locationlog               | ref    | locationlog_view_mac,locationlog_end_time         | locationlog_view_mac | 25      | pf.node.mac,const      |    1 | Using where                                        |
|    1 | PRIMARY            | locationlog2              | ref    | PRIMARY,locationlog_view_mac,locationlog_end_time | locationlog_view_mac | 25      | pf.node.mac,const      |    1 | Using where; Not exists                            |
|    1 | PRIMARY            | r1                        | ref    | callingstationid                                  | callingstationid     | 52      | pf.node.mac            |    5 | Using where                                        |
|    1 | PRIMARY            | r2                        | ref    | PRIMARY,callingstationid,acctstart_acctstop       | callingstationid     | 52      | pf.node.mac            |    5 | Using where; Not exists                            |
|    2 | DEPENDENT SUBQUERY | ip4log                    | ref    | PRIMARY,ip4log_mac_end_time                       | ip4log_mac_end_time  | 19      | pf.node.mac            |    1 | Using index condition; Using where; Using filesort |
+------+--------------------+---------------------------+--------+---------------------------------------------------+----------------------+---------+------------------------+------+----------------------------------------------------+
10 rows in set (0.00 sec)
```

We need to have the default sorting use an index, in the problematic environment I have, viewing the nodes performs a scan on close to 900K rows and destroys the DB

**Comment by julsemaan** [comment]
I just received confirmation that @jrouzierinverse's fix didn't work and the query is still exactly the same as before the fix.

Fix was applied via maintenance branch and patched cleanly (validated the fix is in /usr/local/pf/html/pfappserver/lib/pfappserver/Model/Search/Node.pm)

**Comment by jrouzierinverse** [comment]
I checked and the query is working in devel and in maintenance what are they sorting the view by?

```sql
SELECT `node`.`mac` AS `mac`,
       `node`.`pid` AS `pid`,
       `node`.`voip` AS `voip`,
       `node`.`bypass_vlan` AS `bypass_vlan`,
       `node`.`status` AS `status`,
       `node`.`category_id` AS `category_id`,
       `node`.`bypass_role_id` AS `bypass_role_id`,
       `node`.`user_agent` AS `user_agent`,
       `node`.`computername` AS `computername`,
       `node`.`last_arp` AS `last_arp`,
       `node`.`last_dhcp` AS `last_dhcp`,
       `node`.`notes` AS `notes`,
       `node`.`tenant_id` AS `tenant_id`,
       IF(lastskip='0000-00-00 00:00:00', '', lastskip) AS `lastskip`,
       IF(detect_date='0000-00-00 00:00:00', '', detect_date) AS `detect_date`,
       IF(regdate='0000-00-00 00:00:00', '', regdate) AS `regdate`,
       IF(unregdate='0000-00-00 00:00:00', '', unregdate) AS `unregdate`,
       IF(last_seen='0000-00-00 00:00:00', '', last_seen) AS `last_seen`,
       IFNULL(node_category.name, '') AS `category`,
       IFNULL(node_category_bypass_role.name, '') AS `bypass_role`,
       IFNULL(device_manufacturer, ' ') AS `device_manufacturer`,
       IFNULL(device_class, ' ') AS `device_class`,
       IFNULL(device_type, ' ') AS `device_type`,
       IFNULL(device_version, ' ') AS `device_version`,
       IF(r1.acctstarttime IS NULL, 'unknown', IF(r1.acctstoptime IS NULL, 'on', 'off')) AS `online`,
       `ip4log`.`ip` AS `last_ip`,
       `locationlog`.`switch` AS `switch_id`,
       `locationlog`.`switch_ip` AS `switch_ip`,
       `locationlog`.`switch_mac` AS `switch_mac`,
       `locationlog`.`port` AS `switch_port`,
       `locationlog`.`ifDesc` AS `switch_port_desc`,
       `locationlog`.`ssid` AS `last_ssid`,
       `tenant`.`name` AS `tenant_name`
FROM node
LEFT OUTER JOIN node_category ON (`node`.`category_id` = `node_category`.`category_id`)
LEFT OUTER JOIN tenant ON (`node`.`tenant_id` = `tenant`.`id`)
LEFT OUTER JOIN `node_category` AS `node_category_bypass_role` ON (`node`.`bypass_role_id` = `node_category_bypass_role`.`category_id`)
LEFT OUTER JOIN ip4log ON ((`ip4log`.`ip` =
                              (SELECT `ip`
                               FROM `ip4log`
                               WHERE `mac` = `node`.`mac`
                                 AND `tenant_id` = `node`.`tenant_id`
                               ORDER BY `start_time` DESC
                               LIMIT 1)
                            AND `ip4log`.`tenant_id` = `node`.`tenant_id`))
LEFT OUTER JOIN locationlog ON ((`locationlog`.`end_time` = ?
                                 AND `locationlog`.`mac` = `node`.`mac`
                                 AND `node`.`tenant_id` = `locationlog`.`tenant_id`))
LEFT OUTER JOIN `locationlog` AS `locationlog2` ON (((`locationlog`.`start_time` < `locationlog2`.`start_time`
                                                      OR `locationlog`.`start_time` IS NULL
                                                      OR (`locationlog`.`start_time` = `locationlog2`.`start_time`
                                                          AND `locationlog`.`id` < `locationlog2`.`id`))
                                                     AND `locationlog2`.`end_time` = ?
                                                     AND `node`.`mac` = `locationlog2`.`mac`
                                                     AND `node`.`tenant_id` = `locationlog2`.`tenant_id`))
LEFT OUTER JOIN `radacct` AS `r1` ON ((`node`.`mac` = `r1`.`callingstationid`
                                       AND `node`.`tenant_id` = `r1`.`tenant_id`))
LEFT OUTER JOIN `radacct` AS `r2` ON (((`r1`.`acctstarttime` < `r2`.`acctstarttime`
                                        OR ((`r1`.`acctstarttime` = `r2`.`acctstarttime`
                                             OR (`r1`.`acctstarttime` IS NULL
                                                 AND `r2`.`acctstarttime` IS NULL))
                                            AND `r1`.`radacctid` < `r2`.`radacctid`))
                                       AND `node`.`mac` = `r2`.`callingstationid`
                                       AND `node`.`tenant_id` = `r2`.`tenant_id`))
WHERE ((`r2`.`radacctid` IS NULL
        AND `locationlog2`.`id` IS NULL))
ORDER BY `tenant_id` ASC,
         `mac` ASC
LIMIT ?
OFFSET ?
```

**Comment by jrouzierinverse** [comment]
What version of packetfence are they using?

**Comment by julsemaan** [comment]
- PacketFence 8.1
- They are just clicking on the "Nodes" tab and eventually get an error

**Comment by jrouzierinverse** [comment]
I am assuming a timeout error?

**Comment by julsemaan** [comment]
Correct

**Comment by extrafu** [comment]
@jrouzierinverse Please review this and provide an updated fix.

**Comment by julsemaan** [comment]
Will wait for confirmation that the new updated fix works and I'll close this

**Comment by julsemaan** [comment]
I've validated the patch has been applied and although the query is updated, it still requires a full table scan anyway...

```
MariaDB [pf]> explain SELECT `node`.`mac` AS `mac`, `node`.`pid` AS `pid`, `node`.`voip` AS `voip`, `node`.`bypass_vlan` AS `bypass_vlan`, `node`.`status` AS `status`, `node`.`category_id` AS `category_id`, `node`.`bypass_role_id` AS `bypass_role_id`, `node`.`user_agent` AS `user_agent`, `node`.`computername` AS `computername`, `node`.`last_arp` AS `last_arp`, `node`.`last_dhcp` AS `last_dhcp`, `node`.`notes` AS `notes`, `node`.`tenant_id` AS `tenant_id`, IF(lastskip='0000-00-00 00:00:00','',lastskip) AS `lastskip`, IF(detect_date='0000-00-00 00:00:00','',detect_date) AS `detect_date`, IF(regdate='0000-00-00 00:00:00','',regdate) AS `regdate`, IF(unregdate='0000-00-00 00:00:00','',unregdate) AS `unregdate`, IF(last_seen='0000-00-00 00:00:00','',last_seen) AS `last_seen`, IFNULL(node_category.name, '') AS `category`, IFNULL(node_category_bypass_role.name, '') AS `bypass_role`, IFNULL(device_manufacturer,' ') AS `device_manufacturer`, IFNULL(device_class,' ') AS `device_class`, IFNULL(device_type,' ') AS `device_type`, IFNULL(device_version,' ') AS `device_version`, IF(r1.acctstarttime IS NULL,'unknown',IF(r1.acctstoptime IS NULL, 'on', 'off')) AS `online`, `ip4log`.`ip` AS `last_ip`, `locationlog`.`switch` AS `switch_id`, `locationlog`.`switch_ip` AS `switch_ip`, `locationlog`.`switch_mac` AS `switch_mac`, `locationlog`.`port` AS `switch_port`, `locationlog`.`ifDesc` AS `switch_port_desc`, `locationlog`.`ssid` AS `last_ssid`, `tenant`.`name` AS `tenant_name` FROM node LEFT OUTER JOIN node_category ON ( `node`.`category_id` = `node_category`.`category_id` ) LEFT OUTER JOIN tenant ON ( `node`.`tenant_id` = `tenant`.`id` ) LEFT OUTER JOIN `node_category` AS `node_category_bypass_role` ON ( `node`.`bypass_role_id` = `node_category_bypass_role`.`category_id` ) LEFT OUTER JOIN ip4log ON ( ( `ip4log`.`ip` = ( SELECT `ip` FROM `ip4log` WHERE `mac` = `node`.`mac` AND `tenant_id` = `node`.`tenant_id`  ORDER BY `start_time` DESC LIMIT 1 ) AND `ip4log`.`tenant_id` = `node`.`tenant_id` ) ) LEFT OUTER JOIN locationlog ON ( ( `locationlog`.`end_time` = '0000-00-00 00:00:00' AND `locationlog`.`mac` = `node`.`mac` AND `node`.`tenant_id` = `locationlog`.`tenant_id` ) ) LEFT OUTER JOIN `locationlog` AS `locationlog2` ON ( ( ( `locationlog`.`start_time` < `locationlog2`.`start_time` OR `locationlog`.`start_time` IS NULL OR ( `locationlog`.`start_time` = `locationlog2`.`start_time` AND `locationlog`.`id` < `locationlog2`.`id` ) ) AND `locationlog2`.`end_time` = '0000-00-00 00:00:00' AND `node`.`mac` = `locationlog2`.`mac` AND `node`.`tenant_id` = `locationlog2`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r1` ON ( ( `node`.`mac` = `r1`.`callingstationid` AND `node`.`tenant_id` = `r1`.`tenant_id` ) ) LEFT OUTER JOIN `radacct` AS `r2` ON ( ( ( `r1`.`acctstarttime` < `r2`.`acctstarttime` OR ( ( `r1`.`acctstarttime` = `r2`.`acctstarttime` OR ( `r1`.`acctstarttime` IS NULL AND `r2`.`acctstarttime` IS NULL ) ) AND `r1`.`radacctid` < `r2`.`radacctid` ) ) AND `node`.`mac` = `r2`.`callingstationid` AND `node`.`tenant_id` = `r2`.`tenant_id` ) ) LIMIT 26 OFFSET 0\G
*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: node
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 824483
        Extra:
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: node_category
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: pf.node.category_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 1
  select_type: PRIMARY
        table: tenant
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: pf.node.tenant_id
         rows: 1
        Extra:
*************************** 4. row ***************************
           id: 1
  select_type: PRIMARY
        table: node_category_bypass_role
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: pf.node.bypass_role_id
         rows: 1
        Extra: Using where
*************************** 5. row ***************************
           id: 1
  select_type: PRIMARY
        table: ip4log
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 51
          ref: pf.node.tenant_id,func
         rows: 1
        Extra: Using where; Using index
*************************** 6. row ***************************
           id: 1
  select_type: PRIMARY
        table: locationlog
         type: ref
possible_keys: locationlog_view_mac,locationlog_end_time
          key: locationlog_view_mac
      key_len: 25
          ref: pf.node.mac,const
         rows: 2
        Extra: Using where
*************************** 7. row ***************************
           id: 1
  select_type: PRIMARY
        table: locationlog2
         type: ref
possible_keys: PRIMARY,locationlog_view_mac,locationlog_end_time
          key: locationlog_view_mac
      key_len: 25
          ref: pf.node.mac,const
         rows: 2
        Extra: Using where
*************************** 8. row ***************************
           id: 1
  select_type: PRIMARY
        table: r1
         type: ALL
possible_keys: callingstationid
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 1
        Extra: Using where; Using join buffer (flat, BNL join)
*************************** 9. row ***************************
           id: 1
  select_type: PRIMARY
        table: r2
         type: ALL
possible_keys: PRIMARY,callingstationid,acctstart_acctstop
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 1
        Extra: Range checked for each record (index map: 0x601)
*************************** 10. row ***************************
           id: 2
  select_type: DEPENDENT SUBQUERY
        table: ip4log
         type: ref
possible_keys: PRIMARY,ip4log_mac_end_time
          key: ip4log_mac_end_time
      key_len: 19
          ref: pf.node.mac
         rows: 1
        Extra: Using index condition; Using where; Using filesort
10 rows in set (0.01 sec)
```

I'm able to replicate this on my dev machine with the latest devel schema.

Could you adjust the query and ensure that it doesn't require a full table scan when we perform the explain before we do a new iteration through the maintenance
