### ISSUE TITLE
Autoreg default security event error

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5853]
The security event autoregister but does not assign any unregdate

````
Sep 28 13:05:32 pf-testing packetfence_httpd.webservices: httpd.webservices(24437) WARN: [mac:00:e0:4c:68:09:e3] Warning: 1265: Data truncated for column 'release_date' at row 1 (pf::dal::db_execute)
````
````
[1100007]
trigger=device::3,device::6,device::7,device::8,device::10,device::12,device::13,device::1
actions=log,autoreg,role
enabled=Y
window=dynamic
access_duration=12h
target_category=default
````
````
*************************** 1. row ***************************
          tenant_id: 1
                mac: 9c:b6:d0:18:53:a1
                pid: lzammit
        category_id: 1
        detect_date: 2020-09-26 15:25:53
            regdate: 2020-09-28 13:07:06
          unregdate: 0000-00-00 00:00:00
           lastskip: 0000-00-00 00:00:00
       time_balance: NULL
  bandwidth_balance: NULL
             status: pending
         user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
       computername: Razer
              notes:
           last_arp: 0000-00-00 00:00:00
          last_dhcp: 2020-09-28 13:10:06
   dhcp_fingerprint: 1,3,6,15,31,33,43,44,46,47,119,121,249,252
  dhcp6_fingerprint:
        dhcp_vendor: MSFT 5.0
   dhcp6_enterprise:
        device_type: Microsoft Windows Kernel 10.0
       device_class: Windows OS
     device_version: 10
       device_score: 95
device_manufacturer: Rivet Networks
        bypass_vlan:
               voip: no
            autoreg: no
          sessionid:
    machine_account: NULL
     bypass_role_id: NULL
          last_seen: 2020-09-28 13:10:06
````

issue with the status ?

![image](https://user-images.githubusercontent.com/5261214/94464250-391a3480-018c-11eb-9407-1cd718a2f1d4.png)
